#!/bin/bash

function zd() {
	dir=$(fd -H -t d | fzf)
	[[ -z "$dir" ]] || cd $dir
}

function zv() {
	file=$(fzf)
	[[ -z "$file" ]] || vim $file
}

function gzd() {
	start=$(pwd)
	git_root=$(git rev-parse --show-toplevel) 
	[[ -z "$git_root" ]] || cd $git_root
	dir=$(fd -t d | fzf)
	[[ -z "$dir" ]] && cd $start || cd $dir
}

function gzv() {
	start=$(pwd)
	git_root=$(git rev-parse --show-toplevel) 
	[[ $? != 0 ]] && return
	[[ -z "$git_root" ]] || cd $git_root
	file=$(fzf)
	[[ -z "$dir" ]] && cd $start || vim $file 
}

function gd() {
	git_root=$(git rev-parse --show-toplevel)
	[[ -z "$git_root" ]] || cd $git_root
}
