#!/bin/bash
pacman -S \
	git \
	vim \
	feh \
	alacritty \
	go \
	inkscape \
	gimp \
	neomutt \
	figlet \

pamac build \
	firefox-nightly \
	spotify \
	gotop \
	zoom \
	discord \
	freetube \
	ttf-iosevka \
	toilet \

# Configure git
git config --global user.name "Sean Brickley"
git config --global user.email "sean@wabr.io"

# Install Rust
curl https://sh.rustup.rs -sSf | sh

mkdir -p $HOME/code $HOME/go/src $HOME/go/bin

ssh keygen -t rsa
